import React from 'react';
import {View,Text,TextInput,Pressable,StyleSheet,ScrollView,ActivityIndicator} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Ionicons} from '@expo/vector-icons';
import {C,shadow} from '../theme';
export function Screen({children,scroll=true}){ const body=scroll?<ScrollView contentContainerStyle={s.body}>{children}</ScrollView>:<View style={s.body}>{children}</View>; return <SafeAreaView style={s.safe} edges={['top']}>{body}</SafeAreaView>; }
export function Header({title,subtitle,right}){return <View style={s.header}><View><Text style={s.brand}>{title}</Text>{subtitle?<Text style={s.sub}>{subtitle}</Text>:null}</View>{right}</View>}
export function Card({children,style}){return <View style={[s.card,style]}>{children}</View>}
export function Metric({label,value,tone='pine'}){return <Card style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={[s.metricValue,{color:C[tone]||C.pine}]}>{value}</Text></Card>}
export function Btn({title,onPress,kind='primary',icon,disabled}){return <Pressable disabled={disabled} onPress={onPress} style={[s.btn,kind==='secondary'&&s.btnSecondary,kind==='danger'&&s.btnDanger,disabled&&{opacity:.5}]}>{icon?<Ionicons name={icon} size={18} color={kind==='primary'?'#fff':C.pine}/>:null}<Text style={[s.btnText,kind!=='primary'&&{color:kind==='danger'?C.red:C.pine}]}>{title}</Text></Pressable>}
export function Field({label,...props}){return <View style={{marginBottom:12}}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#A3A39D" style={s.input} {...props}/></View>}
export function SectionTitle({children}){return <Text style={s.section}>{children}</Text>}
export function Row({title,subtitle,right,onPress,icon}){return <Pressable onPress={onPress} style={s.row}>{icon?<View style={s.rowIcon}><Ionicons name={icon} size={19} color={C.pine}/></View>:null}<View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text>{subtitle?<Text style={s.rowSub}>{subtitle}</Text>:null}</View>{right||<Ionicons name="chevron-forward" size={18} color={C.soft}/>}</Pressable>}
export function Badge({children,tone='green'}){const map={green:[C.mint,C.green],red:[C.redSoft,C.red],gold:[C.goldSoft,C.gold],blue:['#E7EDF3',C.blue]};const [bg,fg]=map[tone]||map.green;return <Text style={[s.badge,{backgroundColor:bg,color:fg}]}>{children}</Text>}
export function Empty({title,text}){return <View style={s.empty}><Ionicons name="leaf-outline" size={34} color={C.gold}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyText}>{text}</Text></View>}
export function Loading(){return <View style={s.loading}><ActivityIndicator color={C.pine}/></View>}
export const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},body:{padding:18,paddingBottom:110},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},brand:{fontSize:28,fontWeight:'800',color:C.pine,letterSpacing:.3},sub:{fontSize:13,color:C.soft,marginTop:2},card:{backgroundColor:C.paper,borderRadius:16,borderWidth:1,borderColor:C.line,padding:16,...shadow},metric:{flex:1,minWidth:'46%'},metricLabel:{fontSize:12,color:C.soft,marginBottom:8},metricValue:{fontSize:20,fontWeight:'800'},btn:{minHeight:48,borderRadius:14,backgroundColor:C.pine,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,paddingHorizontal:16,marginTop:8},btnSecondary:{backgroundColor:'transparent',borderWidth:1,borderColor:C.pine},btnDanger:{backgroundColor:'transparent',borderWidth:1,borderColor:C.red},btnText:{color:'#fff',fontWeight:'700',fontSize:15},label:{fontSize:12,color:C.soft,marginBottom:6},input:{backgroundColor:C.paper,borderWidth:1,borderColor:C.line,borderRadius:12,paddingHorizontal:14,paddingVertical:12,fontSize:15,color:C.ink},section:{fontSize:13,fontWeight:'700',color:C.soft,marginTop:18,marginBottom:9,textTransform:'uppercase',letterSpacing:.6},row:{backgroundColor:C.paper,borderBottomWidth:1,borderBottomColor:C.line,minHeight:68,paddingHorizontal:14,paddingVertical:12,flexDirection:'row',alignItems:'center',gap:12},rowIcon:{width:36,height:36,borderRadius:11,backgroundColor:C.mint,alignItems:'center',justifyContent:'center'},rowTitle:{fontSize:15,fontWeight:'700',color:C.ink},rowSub:{fontSize:12,color:C.soft,marginTop:3},badge:{overflow:'hidden',paddingHorizontal:9,paddingVertical:4,borderRadius:999,fontSize:11,fontWeight:'700'},empty:{alignItems:'center',padding:34},emptyTitle:{fontSize:18,fontWeight:'800',color:C.pine,marginTop:10},emptyText:{fontSize:13,color:C.soft,textAlign:'center',marginTop:5},loading:{padding:40,alignItems:'center'}});
